name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Especifica a distribuição do JDK
        java-version: '11'        # Define a versão do JDK

    - name: Build with Maven
      run: mvn clean install       # Faz o build do projeto

    - name: Run Tests
      run: mvn test                # Executa os testes com Maven

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging
      run: |
        echo "Deploying application to staging..."
        # Comando para deploy, como SCP para copiar arquivos para um servidor, etc.
